# Generated by Django 5.1.7 on 2025-03-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("useremail", models.EmailField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("age", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("date_joined", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
